billiards-love-79 회원정보 수정 API 개발
antop-dev/billiards-love pull request #85
Opened 2021-02-17 22:05 UTC by antop-dev

/init API 에서 서버가 클라이언트로 주는 `AES256` 암호화키를 세션에 저장하도록 함. (더 좋은 방법 없을까?)

2021-02-18 01:06 UTC, insukChoi requested changes

2021-02-18 01:06 UTC, insukChoi commented on back-end/src/main/java/org/antop/billiardslove/Constants.java
> +    public static final String SECRET_KEY = "SECRET_KEY";
이거 소스에 하드코딩 해야하나요? 다른방법 없나..

2021-02-18 01:06 UTC, insukChoi commented on back-end/src/main/java/org/antop/billiardslove/service/MemberModifyService.java
> +    void modify(long id, String nickname, int handicap);
파라미터 2개로 줄일수있을것같아요..
(long id, Request request)

2021-02-18 01:06 UTC, insukChoi commented on back-end/src/test/java/org/antop/billiardslove/api/MemberModifyApiTest.java
> +                .andDo(print())
이건 테스트 이후에 지우는게 나을 것 같아요

2021-02-18 16:00 UTC, antop-dev commented on back-end/src/main/java/org/antop/billiardslove/service/MemberModifyService.java
> +    void modify(long id, String nickname, int handicap);
`Request` 클래스는 **컨트롤러에서만 사용하도록** 설계 되었습니다. 다른 클래스까지 넘어가지 않도록 하였습니다.

2021-02-18 16:02 UTC, antop-dev commented on back-end/src/main/java/org/antop/billiardslove/Constants.java
> +    public static final String SECRET_KEY = "SECRET_KEY";
하드코딩을 하지 않으려고 상수 영역에 하드코딩을 한 건데.... 음...??

2021-02-18 16:09 UTC, antop-dev commented on back-end/src/test/java/org/antop/billiardslove/api/MemberModifyApiTest.java
> +                .andDo(print())
테스트 이후에 왜 지워야 하는지 설명좀... ㅠㅠ

2021-02-18 16:14 UTC, antop-dev commented
[소나큐브에서 나온 결함](https://sonarcloud.io/organizations/antop-dev-github/rules?open=java%3AS3751&rule_key=java%3AS3751) 수정

2021-02-19 05:04 UTC, insukChoi commented on back-end/src/main/java/org/antop/billiardslove/Constants.java
> +    public static final String SECRET_KEY = "SECRET_KEY";
아하 뭔가 방법이 없을까 궁금해서 ㅋㅋㅋ

2021-02-19 05:15 UTC, insukChoi commented on back-end/src/main/java/org/antop/billiardslove/service/MemberModifyService.java
> +    void modify(long id, String nickname, int handicap);
근데 그런의도면 만약 Request가 5개 이상으로 늘어난다면..
파라미터가 계속 증가할것같은데요?..
그냥 전 영역에서 Request 클래스를 같이 공유하는것이 더 낫지 않나요?
아니면 interface를 정의해서 Request가 받아서 interface를 넘기는 방식?

ex)
interface MemberView {
     String nickName;
     int handicap;
}

class MemberRequst implements MemberView {
  @overide
  String nickName;
  
 @override
 int nickName;
}
하고 컨트롤러 > 서비스 넘길때
service.modify(long id, MemberView memberView);   이렇게는 어떤가요?

2021-02-19 05:15 UTC, insukChoi commented on back-end/src/test/java/org/antop/billiardslove/api/MemberModifyApiTest.java
> +                .andDo(print())
빌드 로그가 엄청 쌓이니깐...?

2021-02-19 08:59 UTC, antop-dev commented on back-end/src/main/java/org/antop/billiardslove/service/MemberModifyService.java
> +    void modify(long id, String nickname, int handicap);
1. 서비스에서 인자 클래스를 만들지 않은 이유는 인자가 3개라서 입니다. 회원의 구조가 더 복잡해진다면 클래스로 만들 예정입니다.
 
2. 각 레이어에 넘기는 클래스는 정해져 있습니다.
   * Client -> Controller : Controller 내부 클래스
   * Service <-> Repository : `Entity`, `@Id`
   * Controller <-> Service, 기타 <-> 기타 : Xxx`Dto` 등등

2021-02-19 09:08 UTC, antop-dev commented on back-end/src/test/java/org/antop/billiardslove/api/MemberModifyApiTest.java
> +                .andDo(print())
음....?

2021-02-19 09:18 UTC, insukChoi commented on back-end/src/test/java/org/antop/billiardslove/api/MemberModifyApiTest.java
> +                .andDo(print())
음...?

2021-02-19 09:18 UTC, insukChoi approved these changes

2021-02-21 00:49 UTC, merged